In [ ]:
import sys
from pathlib import Path

# Add project root to Python path
project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from src.feature_engineering import engineer_features

## Loading Preprocessed Data

In [ ]:
preprocessed_path = (
    "../data/preprocessed/train_preprocessed.parquet"
)

df = pd.read_parquet(preprocessed_path)

df.shape

(590540, 421)

In [ ]:
df.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,isFraud
0,86400,4.241327,4,13926,361.0,150.0,1,142.0,1,315.0,...,24.0,260,4,2,2,2,2,1,1735,0
1,86401,3.401197,4,2755,404.0,150.0,2,102.0,1,325.0,...,24.0,260,4,2,2,2,2,1,1735,0
2,86469,4.094345,4,4663,490.0,150.0,4,166.0,2,330.0,...,24.0,260,4,2,2,2,2,1,1735,0
3,86499,3.931826,4,18132,567.0,150.0,2,117.0,2,476.0,...,24.0,260,4,2,2,2,2,1,1735,0
4,86506,3.931826,1,4497,514.0,150.0,2,102.0,1,420.0,...,32.0,164,3,1,0,1,1,2,954,0

In [ ]:
df.columns.to_list()

['TransactionDT',
 'TransactionAmt',
 'ProductCD',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'addr1',
 'addr2',
 'dist1',
 'P_emaildomain',
 'R_emaildomain',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D8',
 'D9',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'V29',
 'V30',
 'V31',
 'V32',
 'V33',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V50',
 'V51',
 'V52',
 'V53',
 'V54',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V75',
 'V76',
 'V77',
 'V78',
 'V79',
 'V80',
 'V81',
 'V82',
 'V83',
 'V84',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V90',
 'V91',
 'V92',
 'V93',
 'V94',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V138',
 'V139',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V279',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V320',
 'V321',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339',
 'id_01',
 'id_02',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_09',
 'id_10',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_19',
 'id_20',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo',
 'isFraud']

In [ ]:
df.dtypes.value_counts()

float64    397
int64       24
Name: count, dtype: int64

## Run Feature Engineering

In [ ]:
engineered_df = engineer_features(
    df=df,
    save=True
)

============================================================
       FEATURE ENGINEERING PIPELINE
============================================================

[Step 1] Using provided DataFrame
         Shape               : (590540, 421)

[Step 2] Time features...

[Feature 1] Creating time features from TransactionDT...
            Created : ['tx_hour', 'tx_day_of_week', 'tx_day_of_month', 'tx_week', 'tx_month', 'tx_is_weekend', 'tx_is_night']

[Step 3] Email features...

[Feature 2] Creating email domain features...
            P_email_freq created
            R_email_freq created
            email_domain_match created
            Created : ['P_email_freq', 'R_email_freq', 'email_domain_match']

[Step 4] Card features...

[Feature 3] Creating card features...
            card_identity_freq created
            card1_freq created
            card2_freq created
            Created : ['card_identity_freq', 'card1_freq', 'card2_freq']

[Step 5] Amount features...

[Feature 4] Creating transaction amount features...
            amt_deviation_card1 created
            amt_to_mean_ratio created
            Created : ['amt_deviation_card1', 'amt_to_mean_ratio']

[Step 6] Frequency features...

[Feature 5] Creating frequency encoding features...
            addr1_freq created
            addr2_freq created
            DeviceInfo_freq created
            Created : ['addr1_freq', 'addr2_freq', 'DeviceInfo_freq']

[Step 7] Aggregation features...

[Feature 6] Creating aggregation features...
            card1 aggregations created
            addr1 aggregations created
            Created : ['card1_tx_count', 'card1_amt_mean', 'card1_amt_std', 'card1_amt_max', 'card1_amt_min', 'addr1_tx_count', 'addr1_amt_mean']

[Step 8] Saving engineered data...

Engineered data saved
Path  : D:\Projects\credit-card-fraud-detection\data\preprocessed\train_engineered.parquet
Shape : (590540, 446)

============================================================
       FEATURE ENGINEERING COMPLETE
       Original features  : 421
       New features added : 25
       Final shape        : (590540, 446)
============================================================

In [ ]:
print("Before:", df.shape)
print("After :", engineered_df.shape)

Before: (590540, 429)
After : (590540, 446)

## Analyze New Features

### Time Features

In [ ]:
engineered_df[
    [
        "tx_hour",
        "tx_day_of_week",
        "tx_is_weekend",
        "tx_is_night"
    ]
].head()

   tx_hour  tx_day_of_week  tx_is_weekend  tx_is_night
0        0               0              0            1
1        0               0              0            1
2        0               0              0            1
3        0               0              0            1
4        0               0              0            1

### Frequency Features

In [ ]:
engineered_df[
    [
        "card1_freq",
        "P_email_freq",
        "addr1_freq"
    ]
].describe()

          card1_freq   P_email_freq     addr1_freq
count  590540.000000  590540.000000  590540.000000
mean     2528.815464  128152.810018   37606.642280
std      3702.655513   84807.477283   38225.728656
min         1.000000      32.000000       1.000000
25%       132.000000   45250.000000    8486.000000
50%       919.000000  100934.000000   20827.000000
75%      3152.000000  228355.000000   42751.000000
max     14932.000000  228355.000000  112041.000000

### Aggregation Features

In [ ]:
engineered_df[
    [
        "card1_tx_count",
        "card1_amt_mean",
        "card1_amt_max"
    ]
].describe()

       card1_tx_count  card1_amt_mean  card1_amt_max
count   590540.000000   590540.000000  590540.000000
mean      2528.815464        4.382960       7.250240
std       3702.655513        0.448242       1.129704
min          1.000000        0.479335       0.479335
25%        132.000000        4.248644       6.320678
50%        919.000000        4.399277       7.640580
75%       3152.000000        4.625644       8.088654
max      14932.000000        8.147853      10.371564

## Checking Missing Values

In [ ]:
missing = engineered_df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

## Check Target Column

In [ ]:
"isFraud" in engineered_df.columns

True

In [ ]:
engineered_df["isFraud"].value_counts()

isFraud
0    569877
1     20663
Name: count, dtype: int64

In [ ]:
engineered_df["isFraud"].value_counts(normalize=True) * 100

isFraud
0    96.500999
1     3.499001
Name: proportion, dtype: float64

## Check Data Types

In [ ]:
engineered_df.dtypes.value_counts()

float64    404
int64       38
int32        4
Name: count, dtype: int64

In [ ]:
engineered_df.select_dtypes(include="object").columns

Index([], dtype='str')

## Check Duplicates

In [ ]:
engineered_df.duplicated().sum()

np.int64(3)

## Check Constant Features

In [ ]:
constant_features = [
    col for col in engineered_df.columns
    if engineered_df[col].nunique() == 1
]

constant_features

[]

In [ ]:
engineered_df.describe()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,addr1_freq,addr2_freq,DeviceInfo_freq,card1_tx_count,card1_amt_mean,card1_amt_std,card1_amt_max,card1_amt_min,addr1_tx_count,addr1_amt_mean
count,5.905400e+05,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,...,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000,590540.000000
mean,7.372311e+06,4.382960,3.220757,9898.734658,362.531959,153.186458,3.266305,199.471611,1.753033,291.653527,...,37606.642280,581882.923538,381946.871179,2528.815464,4.382960,0.809380,7.250240,2.277303,37606.642280,4.382960
std,4.617224e+06,0.937183,1.423926,4901.170153,156.595356,11.322604,1.035866,41.157610,0.449543,95.949345,...,38225.728656,49946.506631,179553.690565,3702.655513,0.448242,0.178590,1.129704,0.853633,38225.728656,0.221012
min,8.640000e+04,0.223943,0.000000,1000.000000,100.000000,100.000000,0.000000,100.000000,0.000000,100.000000,...,1.000000,1.000000,1.000000,1.000000,0.479335,0.000000,0.479335,0.223943,1.000000,1.168859
25%,3.027058e+06,3.791459,3.000000,6019.000000,215.000000,150.000000,2.000000,166.000000,1.000000,205.000000,...,8486.000000,586187.000000,471874.000000,132.000000,4.248644,0.760090,6.320678,1.791759,8486.000000,4.347408
50%,7.306528e+06,4.245190,4.000000,9678.000000,361.000000,150.000000,4.000000,226.000000,2.000000,299.000000,...,20827.000000,586187.000000,471874.000000,919.000000,4.399277,0.792047,7.640580,2.221050,20827.000000,4.454238
75%,1.124662e+07,4.836282,4.000000,14184.000000,512.000000,150.000000,4.000000,226.000000,2.000000,327.000000,...,42751.000000,586187.000000,471874.000000,3152.000000,4.625644,0.884479,8.088654,2.772589,42751.000000,4.527678
max,1.581113e+07,10.371564,4.000000,18396.000000,600.000000,231.000000,4.000000,237.000000,4.000000,540.000000,...,112041.000000,586187.000000,471874.000000,14932.000000,8.147853,3.272626,10.371564,8.147853,112041.000000,7.809586

## Correlation with Target