In [1]:
import sys
from pathlib import Path

# Add project root to Python path
project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import numpy as np
import pandas as pd

In [4]:
from src.train import *

## Load Training Data

In [5]:
df = load_training_data()

[Step 1] Loading training data...
            Shape : (590540, 79)

## Dataset Preview

In [6]:
df.head()

,TransactionAmt,ProductCD,card1,card4,card6,DeviceType,tx_hour,tx_day_of_week,tx_is_weekend,tx_is_night,...,M1,V221,V191,V171,V66,V7,id_35,id_29,id_20,isFraud
0,4.241327,4,13926,1,1,1,0,0,0,1,...,1.0,1.0,1.0,1.0,1.0,1.0,2,2,472.0,0
1,3.401197,4,2755,2,1,1,0,0,0,1,...,1.0,1.0,1.0,1.0,1.0,1.0,2,2,472.0,0
2,4.094345,4,4663,4,2,1,0,0,0,1,...,1.0,1.0,1.0,1.0,1.0,1.0,2,2,472.0,0
3,3.931826,4,18132,2,2,1,0,0,0,1,...,1.0,1.0,1.0,1.0,1.0,1.0,2,2,472.0,0
4,3.931826,1,4497,2,1,2,0,0,0,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1,1,144.0,0

## Target Distribution

In [7]:
df["isFraud"].value_counts()

isFraud
0    569877
1     20663
Name: count, dtype: int64

In [8]:
df["isFraud"].value_counts(normalize=True) * 100

isFraud
0    96.500999
1     3.499001
Name: proportion, dtype: float64

## Split Dataset

In [9]:
X_train, X_test, y_train, y_test = split_data(df)

[Step 2] Splitting data...
            Training data : (472432, 78)
            Testing data  : (118108, 78)

            Class distribution:
isFraud
0    455902
1     16530
Name: count, dtype: int64

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(472432, 78)
(118108, 78)
(472432,)
(118108,)

## Logistic Regression

In [15]:
lr_model = train_logistic_regression(X_train, y_train)

[Model 1] Training Logistic Regression...
            Logistic Regression trained

In [16]:
lr_result = evaluate_model(lr_model, X_test, y_test, "Logistic Regression")

lr_result

============================================================
Evaluating : Logistic Regression
============================================================
ROC-AUC   : 0.7850
Precision : 0.1105
Recall    : 0.6204
F1 Score  : 0.1876

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.82      0.89    113975
           1       0.11      0.62      0.19      4133

    accuracy                           0.81    118108
   macro avg       0.55      0.72      0.54    118108
weighted avg       0.95      0.81      0.87    118108

{'Model': 'Logistic Regression',
 'ROC-AUC': 0.785045559345659,
 'Precision': 0.11051724137931035,
 'Recall': 0.6203726106944109,
 'F1 Score': 0.18761204404931767}

## Decision Tree

In [17]:
dt_model = train_decision_tree(X_train, y_train)

[Model 2] Training Decision Tree...
            Decision Tree trained

In [18]:
dt_result = evaluate_model(dt_model, X_test, y_test, "Decision Tree")

dt_result

============================================================
Evaluating : Decision Tree
============================================================
ROC-AUC   : 0.7973
Precision : 0.1434
Recall    : 0.5884
F1 Score  : 0.2306

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.87      0.92    113975
           1       0.14      0.59      0.23      4133

    accuracy                           0.86    118108
   macro avg       0.56      0.73      0.58    118108
weighted avg       0.95      0.86      0.90    118108

{'Model': 'Decision Tree',
 'ROC-AUC': 0.7973498704805723,
 'Precision': 0.14342159580114408,
 'Recall': 0.5884345511734818,
 'F1 Score': 0.23063063063063063}

## Random Forest

In [22]:
rf_model = train_random_forest(X_train, y_train)

[Model 3] Training Random Forest...
            Random Forest trained

In [23]:
rf_result = evaluate_model(rf_model, X_test, y_test, "Random Forest")

============================================================
Evaluating : Random Forest
============================================================
ROC-AUC   : 0.8416
Precision : 0.1900
Recall    : 0.6167
F1 Score  : 0.2906

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.90      0.94    113975
           1       0.19      0.62      0.29      4133

    accuracy                           0.89    118108
   macro avg       0.59      0.76      0.62    118108
weighted avg       0.96      0.89      0.92    118108

## XGBoost

In [24]:
xgb_model = train_xgboost(X_train, y_train)

[Model 4] Training XGBoost...
            scale_pos_weight : 27.58
            XGBoost trained

In [25]:
xgb_result = evaluate_model(xgb_model, X_test, y_test, "XGBoost")

============================================================
Evaluating : XGBoost
============================================================
ROC-AUC   : 0.8668
Precision : 0.1624
Recall    : 0.6804
F1 Score  : 0.2622

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.87      0.93    113975
           1       0.16      0.68      0.26      4133

    accuracy                           0.87    118108
   macro avg       0.57      0.78      0.59    118108
weighted avg       0.96      0.87      0.90    118108

## LightGBM

In [26]:
lgb_model = train_lightgbm(X_train, y_train)

[Model 5] Training LightGBM...
[LightGBM] [Info] Number of positive: 16530, number of negative: 455902
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.079623 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2395
[LightGBM] [Info] Number of data points in the train set: 472432, number of used features: 77
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
            LightGBM trained

In [27]:
lgb_result = evaluate_model(lgb_model, X_test, y_test, "LightGBM")

============================================================
Evaluating : LightGBM
============================================================
ROC-AUC   : 0.8787
Precision : 0.1721
Recall    : 0.6990
F1 Score  : 0.2763

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.88      0.93    113975
           1       0.17      0.70      0.28      4133

    accuracy                           0.87    118108
   macro avg       0.58      0.79      0.60    118108
weighted avg       0.96      0.87      0.91    118108

## CatBoost

In [28]:
cat_model = train_catboost(X_train, y_train)

[Model 6] Training CatBoost...
0:	total: 244ms	remaining: 2m 1s
100:	total: 9.44s	remaining: 37.3s
200:	total: 18s	remaining: 26.8s
300:	total: 26.4s	remaining: 17.5s
400:	total: 35.5s	remaining: 8.76s
499:	total: 44.1s	remaining: 0us
            CatBoost trained

In [29]:
cat_result = evaluate_model(cat_model, X_test, y_test, "CatBoost")

============================================================
Evaluating : CatBoost
============================================================
ROC-AUC   : 0.8544
Precision : 0.1484
Recall    : 0.6797
F1 Score  : 0.2436

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.86      0.92    113975
           1       0.15      0.68      0.24      4133

    accuracy                           0.85    118108
   macro avg       0.57      0.77      0.58    118108
weighted avg       0.96      0.85      0.89    118108

## Compare All Models

In [30]:
results = [
    lr_result,
    dt_result,
    rf_result,
    xgb_result,
    lgb_result,
    cat_result
]

results_df = compare_models(results)

results_df

============================================================
MODEL COMPARISON
============================================================
                 Model   ROC-AUC  Precision    Recall  F1 Score
0             LightGBM  0.878708   0.172149  0.699008  0.276261
1              XGBoost  0.866805   0.162365  0.680377  0.262167
2             CatBoost  0.854430   0.148397  0.679652  0.243604
3        Random Forest  0.841567   0.190040  0.616743  0.290551
4        Decision Tree  0.797350   0.143422  0.588435  0.230631
5  Logistic Regression  0.785046   0.110517  0.620373  0.187612

                 Model   ROC-AUC  Precision    Recall  F1 Score
0             LightGBM  0.878708   0.172149  0.699008  0.276261
1              XGBoost  0.866805   0.162365  0.680377  0.262167
2             CatBoost  0.854430   0.148397  0.679652  0.243604
3        Random Forest  0.841567   0.190040  0.616743  0.290551
4        Decision Tree  0.797350   0.143422  0.588435  0.230631
5  Logistic Regression  0.785046   0.110517  0.620373  0.187612

## Best Model

In [31]:
results_df.iloc[0]

Model        LightGBM
ROC-AUC      0.878708
Precision    0.172149
Recall       0.699008
F1 Score     0.276261
Name: 0, dtype: object

## Model Training Summary

- Six classification models were trained and evaluated.
- ROC-AUC was used as the primary evaluation metric because the dataset is highly imbalanced.
- Precision, Recall, and F1-score were also considered.
- LightGBM achieved the highest ROC-AUC and provided the best balance between performance and training time.
- Therefore, LightGBM was selected for hyperparameter tuning in the next stage.